GetMeInTheMood/Models/Mood.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetMeInTheMood.Models
{
    public class Mood
    {
        public int ID { get; set; }
    
        public string name { get; set; }

        public string imageUrl { get; set; }

        public List<Playlist> Playlists { get; set; }
    }
}

GetMeInTheMood/Models/Playlist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetMeInTheMood.Models
{
    public class Playlist
    {
        public int ID { get; set; }

        public string name { get; set; }

        public User user { get; set; }

        public List<Song> songs { get; set; }

        public Mood mood { get; set; }

    }
}

GetMeInTheMood/Models/Song.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GetMeInTheMood.Models
{
    public class Song
    {
        public int ID { get; set; }

        public string url { get; set; }

        public string status { get; set; }

        public List<Playlist> playlists { get; set; }

    }
}

GetMeInTheMood/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GetMeInTheMood.Models
{
    public class User
    {
        public int ID { get; set; }

        [Required]
        [StringLength(160, MinimumLength = 8)]
        public string email { get; set; }

        [Required]
        [StringLength(160, MinimumLength = 2)]
        public string username { get; set; }

        [Required]
        [StringLength(160, MinimumLength = 8)]
        public string password { get; set; }        

        public List<Playlist> Playlists { get; set; }

    }
}

GetMeInTheMood/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetMeInTheMood.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Moods()
        {

            return View();
        }

        public ActionResult MostPopular()
        {
            return View();
        }
    }
}

GetMeInTheMood/Controllers/LogRegController.cs
using GetMeInTheMood.DAL;
using GetMeInTheMood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace GetMeInTheMood.Controllers
{
    public class LogRegController : Controller
    {
        private GetMeInTheMoodContext db = new GetMeInTheMoodContext();

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string email,string password)
        {
            email = GetSha256FromString(Request.Form["email"]);
            password = GetSha256FromString(Request.Form["password"]);

            var id = -1;
            if (ModelState.IsValid)
            {
                id = findUser(email);
                User user = db.Users.Find(id);

                if(user!=null)
                {
                    if (user.password == password)
                    {
                        TempData["username"] = user.username;
                        Session["logreg"] = "Success";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                        return View();
                }
                else
                    return HttpNotFound();
            }
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(string username,string email,string password)
        {
            username = Request.Form["username"];
            email = Request.Form["email"];
            password = Request.Form["password1"];

            if(ModelState.IsValid)
            {
                if (""==username || "" == email || ""==password)
                    return View();
                else
                {
                    User user = new User();
                    user.username = username;
                    user.email =  GetSha256FromString(email);
                    user.password = GetSha256FromString(password);

                    db.Users.Add(user);
                    db.SaveChanges();

                    TempData["username"] = user.username;
                    Session["logreg"] = "Success";
                    return RedirectToAction("Index", "Home");
                }
            }

            return View();
        }

        private int findUser(string email)
        {
            foreach(var user in db.Users)
            {
                if (email == user.email)
                    return user.ID;
            }
            return -1;
        }
        private static string GetSha256FromString(string strData)
        {
            var message = Encoding.ASCII.GetBytes(strData);
            SHA256Managed hashString = new SHA256Managed();
            string hex = "";

            var hashValue = hashString.ComputeHash(message);
            foreach (byte x in hashValue)
            {
                hex += String.Format("{0:x2}", x);
            }
            return hex;
        }       
    }
}

GetMeInTheMood/Controllers/MyPlaylistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetMeInTheMood.Controllers
{
    public class MyPlaylistController : Controller
    {
        // GET: MyPlaylists
        public ActionResult Index()
        {
            return View();
        }
    }
}

GetMeInTheMood/Controllers/MyPlaylistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GetMeInTheMood.Controllers
{
    public class MyPlaylistsController : Controller
    {
        // GET: MyPlaylists
        public ActionResult Index()
        {
            return View();
        }
    }
}

GetMeInTheMood/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.Username = TempData["username"];
}
<div class="jumbotron">
    <h1>Get me in the mood</h1>
    <h2>Dobro odrađeno! :D</h2>
</div>

GetMeInTheMood/Views/Home/Moods.cshtml
@{
    ViewBag.Title = "Moods";
}
<h2>@ViewBag.Title.</h2>

<p>Choose your music depending on your mood</p>

GetMeInTheMood/Views/Home/MostPopular.cshtml
@{
    ViewBag.Title = "Most popular";
}
<h2>@ViewBag.Title.</h2>

<p>Most popular playlists</p>

GetMeInTheMood/Views/LogReg/Login.cshtml
@{
    ViewBag.Title = "Log in";
}
<div class="log-reg-form">
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Login", "LogReg","POST"))
{
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email" required >
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" required class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
    </div>
    <button type="submit" class="btn btn-default">Log in</button>
}
</div>

GetMeInTheMood/Views/LogReg/Register.cshtml
@{
    ViewBag.Title = "Register";
}
<div class="log-reg-form">
    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm("Register", "LogReg", "POST"))
    {
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" placeholder="Username" name="username" required>
        </div>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" placeholder="Email" name="email" required>
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" placeholder="Password" name="password1" required>
        </div>
        <div class="form-group">
            <label for="password2">Confirm Password</label>
            <input type="password" class="form-control" id="password2" placeholder="Confirm Password" name="password2" required>
        </div>
        <button type="submit" class="btn btn-default pull-right">Register</button>
    }
</div>

GetMeInTheMood/Views/MyPlaylist/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMyPlaylist.cshtml";
}
@{
    ViewBag.Title = "My Playlist";
}
<h1>Uspio sam!</h1>

GetMeInTheMood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GetMeInTheMood</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li><a href="@Url.Action("Moods", "Home")"><span class="glyphicon glyphicon-music"></span> Moods</a></li>
                    <li><a href="@Url.Action("MostPopular", "Home")"><span class="glyphicon glyphicon-star"></span> MostPopular</a></li>
                    @{ if (Session["logreg"] != null)
                        {
                            <li><a href="@Url.Action("Index", "MyPlaylist")"><span class="glyphicon glyphicon-th-list"></span> My playlist</a></li>
                        }
                    }              
                </ul>
                <ul class="nav navbar-nav pull-right" >
                    @{ if (Session["logreg"] == null)
                        {
                            <li>@Html.ActionLink("Log in", "Login", "LogReg")</li>
                            <li>@Html.ActionLink("Register", "Register", "LogReg")</li>
                        }
                        else {<li><a><span class="glyphicon glyphicon-user"></span> @ViewBag.Username</a></li>}
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer class="navbar-fixed-bottom">
            <hr />
            <p style="text-align:center"> &copy; @DateTime.Now.Year - Boris Kostreš & Berislav Šapina</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GetMeInTheMood/Views/Shared/_LayoutMyPlaylist.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GetMeInTheMood</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span> Home</a></li>
                    <li><a href="@Url.Action("Moods", "Home")"><span class="glyphicon glyphicon-music"></span> Moods</a></li>
                    <li><a href="@Url.Action("MostPopular", "Home")"><span class="glyphicon glyphicon-star"></span> MostPopular</a></li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li><a><span class="glyphicon glyphicon-user"></span>@TempData["username"]</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Boris Kostreš & Berislav Šapina</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>